In [1]:
import tensorflow as tf
from tensorflow.keras import models, layers
import matplotlib.pyplot as plt
from IPython.display import HTML

from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [2]:
IMAGE_SIZE = 256
CHANNELS = 3
    
train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=10,
    horizontal_flip=True)

train_generator = train_datagen.flow_from_directory(
    'dataset/train',
    target_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=32,
    class_mode="sparse"
)

Found 1506 images belonging to 3 classes.


In [3]:
for image_batch, label_batch in train_generator:
    print(image_batch[0])
    break

[[[0.74251914 0.6876172  0.7464407 ]
  [0.78412247 0.7292205  0.78804404]
  [0.8120594  0.75715744 0.815981  ]
  ...
  [0.6755844  0.6206824  0.6873491 ]
  [0.67471147 0.61980945 0.6864762 ]
  [0.6738385  0.61893654 0.6856032 ]]

 [[0.7407733  0.68587136 0.7446949 ]
  [0.78041255 0.7255106  0.7843341 ]
  [0.8157693  0.76086736 0.8196909 ]
  ...
  [0.66345084 0.6085488  0.67521554]
  [0.66366905 0.6087671  0.67543375]
  [0.66388726 0.6089853  0.67565197]]

 [[0.7390275  0.68412554 0.74294907]
  [0.77670264 0.7218007  0.7806242 ]
  [0.8194792  0.76457727 0.8234008 ]
  ...
  [0.6680659  0.61316395 0.6798306 ]
  [0.6685024  0.61360043 0.6802671 ]
  [0.6689388  0.61403686 0.6807035 ]]

 ...

 [[0.65427923 0.58761257 0.62682825]
  [0.6551522  0.58848554 0.6277012 ]
  [0.6560251  0.58935845 0.62857413]
  ...
  [0.61316395 0.5425757  0.58963454]
  [0.605333   0.53474474 0.58180356]
  [0.6071314  0.53654313 0.583602  ]]

 [[0.642147   0.57548034 0.614696  ]
  [0.64083767 0.57417095 0.6133867 ]


In [4]:
train_generator.class_indices

{'Potato___Early_blight': 0, 'Potato___Late_blight': 1, 'Potato___healthy': 2}

In [5]:
class_names = list(train_generator.class_indices.keys())

In [6]:
train_generator.classes.shape

(1506,)

In [7]:
validation_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=10,
    horizontal_flip=True)

validation_generator = train_datagen.flow_from_directory(
    'dataset/val',
    target_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=32,
    class_mode="sparse"
)

Found 215 images belonging to 3 classes.


In [8]:
test_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=10,
    horizontal_flip=True)

test_generator = train_datagen.flow_from_directory(
    'dataset/test',
    target_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=32,
    class_mode="sparse"
)

Found 431 images belonging to 3 classes.


# MODEL BUILDING

In [9]:
input_shape = (IMAGE_SIZE,IMAGE_SIZE,CHANNELS)
n_classes = 3

model = models.Sequential([
    layers.InputLayer(input_shape),
    layers.Conv2D(32, kernel_size=(3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64, kernel_size=(3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64, kernel_size=(3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64, kernel_size=(3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64, kernel_size=(3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64, kernel_size=(3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(n_classes, activation= 'softmax'),
    
])


In [10]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 254, 254, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 127, 127, 32)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 125, 125, 64)   │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 62, 62, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 60, 60, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 30, 30, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 28, 28, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_3 (MaxPooling2D)  │ (None, 14, 14, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_4 (Conv2D)               │ (None, 12, 12, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_4 (MaxPooling2D)  │ (None, 6, 6, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_5 (Conv2D)               │ (None, 4, 4, 64)       │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_5 (MaxPooling2D)  │ (None, 2, 2, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 64)             │        16,448 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 3)              │           195 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 183,747 (717.76 KB)

 Trainable params: 183,747 (717.76 KB)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.compile(
    optimizer='adam',
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    metrics=['accuracy']
)

In [12]:
model.fit(
    train_generator,
    steps_per_epoch=47,
    batch_size=32,
    validation_data=validation_generator,
    validation_steps=6,
    verbose=1,
    epochs=20
)


C:\Users\ansh4\anaconda3\anaconda\Lib\site-packages\keras\src\trainers\data_adapters\py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


Epoch 1/20
47/47 ━━━━━━━━━━━━━━━━━━━━ 45s 890ms/step - accuracy: 0.4778 - loss: 0.9692 - val_accuracy: 0.5156 - val_loss: 0.8895
Epoch 2/20
 1/47 ━━━━━━━━━━━━━━━━━━━━ 27s 594ms/step - accuracy: 0.4688 - loss: 0.7994

C:\Users\ansh4\anaconda3\anaconda\Lib\site-packages\keras\src\trainers\epoch_iterator.py:107: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self._interrupted_warning()


47/47 ━━━━━━━━━━━━━━━━━━━━ 3s 59ms/step - accuracy: 0.4688 - loss: 0.7994 - val_accuracy: 0.4948 - val_loss: 0.8916
Epoch 3/20
47/47 ━━━━━━━━━━━━━━━━━━━━ 42s 884ms/step - accuracy: 0.5242 - loss: 0.8607 - val_accuracy: 0.6667 - val_loss: 0.7376
Epoch 4/20
47/47 ━━━━━━━━━━━━━━━━━━━━ 3s 56ms/step - accuracy: 0.6250 - loss: 0.8028 - val_accuracy: 0.6615 - val_loss: 0.7257
Epoch 5/20
47/47 ━━━━━━━━━━━━━━━━━━━━ 40s 844ms/step - accuracy: 0.7213 - loss: 0.6367 - val_accuracy: 0.7344 - val_loss: 0.6016
Epoch 6/20
47/47 ━━━━━━━━━━━━━━━━━━━━ 3s 57ms/step - accuracy: 0.7500 - loss: 0.5002 - val_accuracy: 0.7552 - val_loss: 0.5633
Epoch 7/20
47/47 ━━━━━━━━━━━━━━━━━━━━ 39s 831ms/step - accuracy: 0.7789 - loss: 0.5376 - val_accuracy: 0.8021 - val_loss: 0.4257
Epoch 8/20
47/47 ━━━━━━━━━━━━━━━━━━━━ 3s 62ms/step - accuracy: 0.9062 - loss: 0.2701 - val_accuracy: 0.8073 - val_loss: 0.4189
Epoch 9/20
47/47 ━━━━━━━━━━━━━━━━━━━━ 39s 856ms/step - accuracy: 0.8245 - loss: 0.4264 - val_accuracy: 0.8490 - val_

In [13]:
scores = model.evaluate(test_generator)

14/14 ━━━━━━━━━━━━━━━━━━━━ 6s 434ms/step - accuracy: 0.9401 - loss: 0.1226


In [14]:
scores

[0.1380147486925125, 0.94199538230896]

In [17]:
model.export("potatoes_saved_model")



INFO:tensorflow:Assets written to: potatoes_saved_model\assets


INFO:tensorflow:Assets written to: potatoes_saved_model\assets


Saved artifact at 'potatoes_saved_model'. The following endpoints are available:

* Endpoint 'serve'
  args_0 (POSITIONAL_ONLY): TensorSpec(shape=(None, 256, 256, 3), dtype=tf.float32, name='keras_tensor')
Output Type:
  TensorSpec(shape=(None, 3), dtype=tf.float32, name=None)
Captures:
  2314641277584: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2314641277200: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2314641277776: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2314637271952: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2314637272336: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2314637272528: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2314641278928: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2314637272912: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2314637278672: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2314637268688: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2314637278864: TensorSpec(shap